"""create core data model

Revision ID: 212cd836c4bd
Revises: 
Create Date: 2026-05-14 15:23:26.349176
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '212cd836c4bd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('code', name=op.f('uq_tenants_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'external_id', name='uq_users_tenant_external')
    )
    op.create_index('idx_users_tenant_status', 'users', ['tenant_id', 'status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('purchaser', sa.String(length=300), nullable=True),
    sa.Column('agency', sa.String(length=300), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('region_code', sa.String(length=64), nullable=True),
    sa.Column('industry_code', sa.String(length=64), nullable=True),
    sa.Column('notice_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bid_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'pending_files', 'parsing', 'pending_confirm', 'need_materials', 'confirmed', 'exported', 'archived')", name=op.f('ck_projects_project_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_projects_created_by_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('idx_projects_tenant_name', 'projects', ['tenant_id', 'name'], unique=False)
    op.create_index('idx_projects_tenant_status_deadline', 'projects', ['tenant_id', 'status', 'bid_deadline_at'], unique=False)
    op.create_table('bid_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bid_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_files', 'parsing', 'pending_confirm', 'need_materials', 'confirmed', 'exported', 'archived')", name=op.f('ck_bid_sections_bid_section_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_bid_sections_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_bid_sections_project_id_projects')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_bid_sections_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bid_sections'))
    )
    op.create_index('idx_bid_sections_tenant_project', 'bid_sections', ['tenant_id', 'project_id'], unique=False)
    op.create_index('idx_bid_sections_tenant_status', 'bid_sections', ['tenant_id', 'status'], unique=False)
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_project_members_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_members_project_id_projects')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_project_members_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_members')),
    sa.UniqueConstraint('tenant_id', 'project_id', 'user_id', 'role_code', name=op.f('uq_project_members_tenant_id'))
    )
    op.create_index('idx_project_members_project', 'project_members', ['tenant_id', 'project_id', 'status'], unique=False)
    op.create_index('idx_project_members_user', 'project_members', ['tenant_id', 'user_id', 'status'], unique=False)
    op.create_table('async_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('input_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'retrying', 'succeeded', 'failed', 'canceled')", name=op.f('ck_async_tasks_async_task_status_allowed')),
    sa.CheckConstraint("task_type IN ('file_acquisition', 'document_parse', 'matrix_generate', 'excel_export')", name=op.f('ck_async_tasks_async_task_type_allowed')),
    sa.CheckConstraint('max_retries >= 0', name=op.f('ck_async_tasks_async_task_max_retries_non_negative')),
    sa.CheckConstraint('progress >= 0 AND progress <= 100', name=op.f('ck_async_tasks_async_task_progress_range')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_async_tasks_async_task_retry_count_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_async_tasks_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_async_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_async_tasks_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_async_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_async_tasks')),
    sa.UniqueConstraint('tenant_id', 'task_type', 'idempotency_key', name=op.f('uq_async_tasks_tenant_id'))
    )
    op.create_index('idx_async_tasks_type_status', 'async_tasks', ['tenant_id', 'task_type', 'status', 'created_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'system', 'worker')", name=op.f('ck_audit_logs_audit_log_actor_type_allowed')),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name=op.f('ck_audit_logs_audit_log_severity_allowed')),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_audit_logs_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_audit_logs_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_action_time', 'audit_logs', ['tenant_id', 'action', 'created_at'], unique=False)
    op.create_index('idx_audit_object', 'audit_logs', ['tenant_id', 'object_type', 'object_id', 'created_at'], unique=False)
    op.create_index('idx_audit_tenant_project_time', 'audit_logs', ['tenant_id', 'project_id', 'created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_site', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_ext', sa.String(length=32), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("doc_type IN ('tender', 'clarification', 'attachment', 'enterprise_material', 'export')", name=op.f('ck_documents_document_doc_type_allowed')),
    sa.CheckConstraint("source_type IN ('upload', 'public_url', 'manual_import')", name=op.f('ck_documents_document_source_type_allowed')),
    sa.CheckConstraint("status IN ('pending', 'available', 'parsing', 'parse_failed', 'deleted')", name=op.f('ck_documents_document_status_allowed')),
    sa.CheckConstraint('file_size >= 0', name=op.f('ck_documents_document_file_size_non_negative')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_documents_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_documents_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_documents_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_documents_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('idx_documents_source_url_hash', 'documents', ['tenant_id', 'source_type', 'sha256'], unique=False)
    op.create_index('idx_documents_tenant_project_section', 'documents', ['tenant_id', 'project_id', 'section_id'], unique=False)
    op.create_index('idx_documents_tenant_sha256', 'documents', ['tenant_id', 'sha256'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('parse_status', sa.String(length=32), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=True),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parse_status IN ('pending', 'parsing', 'succeeded', 'failed', 'frozen')", name=op.f('ck_document_versions_document_version_parse_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_document_versions_created_by_users')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_versions_document_id_documents')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_versions_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('tenant_id', 'document_id', 'version_no', name=op.f('uq_document_versions_tenant_id'))
    )
    op.create_index('idx_document_versions_tenant_document', 'document_versions', ['tenant_id', 'document_id'], unique=False)
    op.create_foreign_key(
        'fk_documents_current_version_id_document_versions',
        'documents',
        'document_versions',
        ['current_version_id'],
        ['id'],
    )
    op.create_table('export_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('export_type', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('bucket', sa.String(length=128), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('filter_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_snapshot_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("export_type IN ('compliance_matrix_excel')", name=op.f('ck_export_files_export_file_type_allowed')),
    sa.CheckConstraint("status IN ('generating', 'available', 'failed', 'deleted')", name=op.f('ck_export_files_export_file_status_allowed')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_export_files_created_by_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_export_files_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_export_files_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['task_id'], ['async_tasks.id'], name=op.f('fk_export_files_task_id_async_tasks')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_export_files_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_files'))
    )
    op.create_index('idx_export_files_project', 'export_files', ['tenant_id', 'project_id', 'section_id'], unique=False)
    op.create_index('idx_export_files_task', 'export_files', ['tenant_id', 'task_id'], unique=False)
    op.create_table('file_acquisition_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=True),
    sa.Column('source_site', sa.String(length=200), nullable=True),
    sa.Column('fetch_method', sa.String(length=64), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('content_length', sa.BigInteger(), nullable=True),
    sa.Column('redirect_chain_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('target_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fetch_method IN ('manual_public_url')", name=op.f('ck_file_acquisition_tasks_file_acquisition_fetch_method_allowed')),
    sa.CheckConstraint("validation_status IN ('pending', 'allowed', 'blocked')", name=op.f('ck_file_acquisition_tasks_file_acquisition_validation_status_allowed')),
    sa.CheckConstraint('content_length IS NULL OR content_length >= 0', name=op.f('ck_file_acquisition_tasks_file_acquisition_content_length_non_negative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_file_acquisition_tasks_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_file_acquisition_tasks_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['target_document_id'], ['documents.id'], name=op.f('fk_file_acquisition_tasks_target_document_id_documents')),
    sa.ForeignKeyConstraint(['task_id'], ['async_tasks.id'], name=op.f('fk_file_acquisition_tasks_task_id_async_tasks')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_file_acquisition_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_file_acquisition_tasks'))
    )
    op.create_index('idx_file_acq_project', 'file_acquisition_tasks', ['tenant_id', 'project_id', 'section_id'], unique=False)
    op.create_index('idx_file_acq_task', 'file_acquisition_tasks', ['tenant_id', 'task_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('heading_path', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('bbox_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_document_chunks_document_version_id_document_versions')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_document_chunks_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_document_chunks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks'))
    )
    op.create_index('idx_chunks_tenant_document_index', 'document_chunks', ['tenant_id', 'document_id', 'chunk_index'], unique=False)
    op.create_index('idx_chunks_tenant_version_page', 'document_chunks', ['tenant_id', 'document_version_id', 'page_no'], unique=False)
    op.create_table('parse_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('document_version_id', sa.UUID(), nullable=False),
    sa.Column('parser_type', sa.String(length=64), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=False),
    sa.Column('parser_version', sa.String(length=64), nullable=True),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("parser_type IN ('pdf_text', 'word', 'ocr', 'excel')", name=op.f('ck_parse_tasks_parse_task_parser_type_allowed')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_parse_tasks_document_id_documents')),
    sa.ForeignKeyConstraint(['document_version_id'], ['document_versions.id'], name=op.f('fk_parse_tasks_document_version_id_document_versions')),
    sa.ForeignKeyConstraint(['task_id'], ['async_tasks.id'], name=op.f('fk_parse_tasks_task_id_async_tasks')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_parse_tasks_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parse_tasks'))
    )
    op.create_index('idx_parse_tasks_document', 'parse_tasks', ['tenant_id', 'document_id', 'document_version_id'], unique=False)
    op.create_index('idx_parse_tasks_task', 'parse_tasks', ['tenant_id', 'task_id'], unique=False)
    op.create_table('compliance_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('source_version_id', sa.UUID(), nullable=False),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True),
    sa.Column('source_page_no', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=64), nullable=False),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('normalized_requirement', sa.Text(), nullable=True),
    sa.Column('response_suggestion', sa.Text(), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('is_batch_confirm_allowed', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confirmed_by', sa.UUID(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modify_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("is_batch_confirm_allowed = false OR (risk_level != 'high' AND is_mandatory = false AND status != 'needs_material')", name=op.f('ck_compliance_items_compliance_batch_confirm_guard')),
    sa.CheckConstraint("item_type IN ('qualification', 'mandatory_response', 'format', 'deadline', 'scoring', 'other')", name=op.f('ck_compliance_items_compliance_item_type_allowed')),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name=op.f('ck_compliance_items_compliance_item_risk_level_allowed')),
    sa.CheckConstraint("status != 'confirmed' OR source_chunk_id IS NOT NULL", name=op.f('ck_compliance_items_compliance_confirmed_requires_source_chunk')),
    sa.CheckConstraint("status IN ('draft', 'pending_confirm', 'confirmed', 'needs_material', 'rejected', 'superseded')", name=op.f('ck_compliance_items_compliance_item_status_allowed')),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 1)', name=op.f('ck_compliance_items_compliance_item_confidence_score_range')),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_compliance_items_confirmed_by_users')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_compliance_items_created_by_users')),
    sa.ForeignKeyConstraint(['modified_by'], ['users.id'], name=op.f('fk_compliance_items_modified_by_users')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_compliance_items_owner_user_id_users')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_compliance_items_project_id_projects')),
    sa.ForeignKeyConstraint(['section_id'], ['bid_sections.id'], name=op.f('fk_compliance_items_section_id_bid_sections')),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], name=op.f('fk_compliance_items_source_chunk_id_document_chunks')),
    sa.ForeignKeyConstraint(['source_document_id'], ['documents.id'], name=op.f('fk_compliance_items_source_document_id_documents')),
    sa.ForeignKeyConstraint(['source_version_id'], ['document_versions.id'], name=op.f('fk_compliance_items_source_version_id_document_versions')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_compliance_items_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_items'))
    )
    op.create_index('idx_cm_filter', 'compliance_items', ['tenant_id', 'project_id', 'section_id', 'status', 'risk_level', 'owner_user_id'], unique=False)
    op.create_index('idx_cm_source', 'compliance_items', ['tenant_id', 'source_document_id', 'source_version_id', 'source_chunk_id'], unique=False)
    op.create_index('idx_cm_tenant_project_section', 'compliance_items', ['tenant_id', 'project_id', 'section_id'], unique=False)
    op.create_index('idx_cm_updated', 'compliance_items', ['tenant_id', 'project_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cm_updated', table_name='compliance_items')
    op.drop_index('idx_cm_tenant_project_section', table_name='compliance_items')
    op.drop_index('idx_cm_source', table_name='compliance_items')
    op.drop_index('idx_cm_filter', table_name='compliance_items')
    op.drop_table('compliance_items')
    op.drop_index('idx_parse_tasks_task', table_name='parse_tasks')
    op.drop_index('idx_parse_tasks_document', table_name='parse_tasks')
    op.drop_table('parse_tasks')
    op.drop_index('idx_chunks_tenant_version_page', table_name='document_chunks')
    op.drop_index('idx_chunks_tenant_document_index', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_file_acq_task', table_name='file_acquisition_tasks')
    op.drop_index('idx_file_acq_project', table_name='file_acquisition_tasks')
    op.drop_table('file_acquisition_tasks')
    op.drop_index('idx_export_files_task', table_name='export_files')
    op.drop_index('idx_export_files_project', table_name='export_files')
    op.drop_table('export_files')
    op.drop_index('idx_document_versions_tenant_document', table_name='document_versions')
    op.drop_constraint(
        'fk_documents_current_version_id_document_versions',
        'documents',
        type_='foreignkey',
    )
    op.drop_table('document_versions')
    op.drop_index('idx_documents_tenant_sha256', table_name='documents')
    op.drop_index('idx_documents_tenant_project_section', table_name='documents')
    op.drop_index('idx_documents_source_url_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_audit_tenant_project_time', table_name='audit_logs')
    op.drop_index('idx_audit_object', table_name='audit_logs')
    op.drop_index('idx_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_async_tasks_type_status', table_name='async_tasks')
    op.drop_table('async_tasks')
    op.drop_index('idx_project_members_user', table_name='project_members')
    op.drop_index('idx_project_members_project', table_name='project_members')
    op.drop_table('project_members')
    op.drop_index('idx_bid_sections_tenant_status', table_name='bid_sections')
    op.drop_index('idx_bid_sections_tenant_project', table_name='bid_sections')
    op.drop_table('bid_sections')
    op.drop_index('idx_projects_tenant_status_deadline', table_name='projects')
    op.drop_index('idx_projects_tenant_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_users_tenant_status', table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###
